name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.0.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Test type definitions
        run: pnpm tsd

      - name: Test
        run: set -o pipefail && pnpm test | tee ./previous-test-output.tap

      - name: Create summary
        uses: actions/github-script@v7
        with:
          script: |
            const { createTestSummary } = await import("${{ github.workspace }}/.github/workflows/summary.js")

            await createTestSummary()
